# 動態網頁爬蟲 - 使用 Selenium

* 了解 Selenium 用於動態網頁爬蟲的原理
* 能夠使用 Selenium 撰寫動態網頁爬蟲

## 作業目標


* 取出 台北市萬華區 2019/01 – 2019/07 的 table 資料

In [1]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select
import pandas as pd
from io import StringIO
import time

In [2]:
browser = webdriver.Chrome(executable_path='../chromedriver')
browser.get("https://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")
#browser.close

In [3]:
selectSite = Select(browser.find_element_by_id("ctl05_ddlSite"))
selectSite.select_by_value('13')
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2019')
browser.find_element_by_id('ctl05_btnQuery').click()
time.sleep(5) #若不設定間格時間去接執行，則html_source抓到的網頁為上為查詢之網頁，會找不到表格
html_source = browser.page_source
#html_source

In [4]:
pd.__version__

'0.25.1'

In [39]:
dfs = pd.read_html(html_source)
# 先篩選欄位為5的表格，再做選取
df = [df for df in dfs if df.shape[1] == 5]
df = df[1]
df

    監測項目   單位     監測日期    監測值    標註
0    SO2  ppb  2019/01   1.90   NaN
1    SO2  ppb  2019/02   2.00   NaN
2    SO2  ppb  2019/03   1.90   NaN
3    SO2  ppb  2019/04   2.50   NaN
4    SO2  ppb  2019/05   2.00   NaN
..   ...  ...      ...    ...   ...
75   NO2  ppb  2019/10  17.96   NaN
76   NO2  ppb  2019/11  19.64   NaN
77   THC  ppm      NaN    NaN  無此測項
78  NMHC  ppm      NaN    NaN  無此測項
79   CH4  ppm      NaN    NaN  無此測項

[80 rows x 5 columns]

In [6]:
from datetime import datetime

https://blog.csdn.net/ls13552912394/article/details/79328762

In [7]:
#法一

#先把'監測日期'轉為datetime再設為index(反向操作亦可)

df['監測日期']=pd.to_datetime(df['監測日期'],errors='coerce')
# df['監測日期'] = df['監測日期'].dt.strftime('%m / %Y') 僅把"間測日期"改為字串格式，若再設定為index則不能使用時間去做篩選(因類型為object)
# df.index = pd.DatetimeIndex(df.index) 可把object類型之index轉為datetime
df = df.set_index(['監測日期'])
df

            監測項目   單位    監測值    標註
監測日期
2019-01-01   SO2  ppb   1.90   NaN
2019-02-01   SO2  ppb   2.00   NaN
2019-03-01   SO2  ppb   1.90   NaN
2019-04-01   SO2  ppb   2.50   NaN
2019-05-01   SO2  ppb   2.00   NaN
...          ...  ...    ...   ...
2019-10-01   NO2  ppb  17.96   NaN
2019-11-01   NO2  ppb  19.64   NaN
NaT          THC  ppm    NaN  無此測項
NaT         NMHC  ppm    NaN  無此測項
NaT          CH4  ppm    NaN  無此測項

[80 rows x 4 columns]

In [8]:
df['2019-1':'2019-7']

            監測項目     單位    監測值   標註
監測日期
2019-01-01   SO2    ppb   1.90  NaN
2019-02-01   SO2    ppb   2.00  NaN
2019-03-01   SO2    ppb   1.90  NaN
2019-04-01   SO2    ppb   2.50  NaN
2019-05-01   SO2    ppb   2.00  NaN
2019-06-01   SO2    ppb   2.00  NaN
2019-07-01   SO2    ppb   1.70  NaN
2019-01-01    CO    ppm   0.57  NaN
2019-02-01    CO    ppm   0.54  NaN
2019-03-01    CO    ppm   0.56  NaN
2019-04-01    CO    ppm   0.59  NaN
2019-05-01    CO    ppm   0.44  NaN
2019-06-01    CO    ppm   0.49  NaN
2019-07-01    CO    ppm   0.41  NaN
2019-01-01    O3    ppb  24.40  NaN
2019-02-01    O3    ppb  25.60  NaN
2019-03-01    O3    ppb  32.20  NaN
2019-04-01    O3    ppb  31.80  NaN
2019-05-01    O3    ppb  30.40  NaN
2019-06-01    O3    ppb  21.30  NaN
2019-07-01    O3    ppb  17.70  NaN
2019-01-01  PM10  μg/m3  31.00  NaN
2019-02-01  PM10  μg/m3  31.00  NaN
2019-03-01  PM10  μg/m3  40.00  NaN
2019-04-01  PM10  μg/m3  38.00  NaN
2019-05-01  PM10  μg/m3  31.00  NaN
2019-06-01  PM10  μg/m3  24.00  NaN
2019-07-01  PM10  μg/m3  22.00  NaN
2019-01-01   NOx    ppb  29.84  NaN
2019-02-01   NOx    ppb  25.26  NaN
2019-03-01   NOx    ppb  28.08  NaN
2019-04-01   NOx    ppb  27.25  NaN
2019-05-01   NOx    ppb  24.45  NaN
2019-06-01   NOx    ppb  25.25  NaN
2019-07-01   NOx    ppb  20.96  NaN
2019-01-01    NO    ppb   7.36  NaN
2019-02-01    NO    ppb   4.85  NaN
2019-03-01    NO    ppb   4.87  NaN
2019-04-01    NO    ppb   4.61  NaN
2019-05-01    NO    ppb   4.51  NaN
2019-06-01    NO    ppb   6.39  NaN
2019-07-01    NO    ppb   5.36  NaN
2019-01-01   NO2    ppb  22.49  NaN
2019-02-01   NO2    ppb  20.41  NaN
2019-03-01   NO2    ppb  23.20  NaN
2019-04-01   NO2    ppb  22.64  NaN
2019-05-01   NO2    ppb  19.94  NaN
2019-06-01   NO2    ppb  18.86  NaN
2019-07-01   NO2    ppb  15.60  NaN

In [40]:
#法2
df = df.set_index('監測日期')
df.index = pd.DatetimeIndex(df.index)
df.loc['2019/01':'2019/07'] # or  df['2019/01':'2019/07']

            監測項目     單位    監測值   標註
監測日期
2019-01-01   SO2    ppb   1.90  NaN
2019-02-01   SO2    ppb   2.00  NaN
2019-03-01   SO2    ppb   1.90  NaN
2019-04-01   SO2    ppb   2.50  NaN
2019-05-01   SO2    ppb   2.00  NaN
2019-06-01   SO2    ppb   2.00  NaN
2019-07-01   SO2    ppb   1.70  NaN
2019-01-01    CO    ppm   0.57  NaN
2019-02-01    CO    ppm   0.54  NaN
2019-03-01    CO    ppm   0.56  NaN
2019-04-01    CO    ppm   0.59  NaN
2019-05-01    CO    ppm   0.44  NaN
2019-06-01    CO    ppm   0.49  NaN
2019-07-01    CO    ppm   0.41  NaN
2019-01-01    O3    ppb  24.40  NaN
2019-02-01    O3    ppb  25.60  NaN
2019-03-01    O3    ppb  32.20  NaN
2019-04-01    O3    ppb  31.80  NaN
2019-05-01    O3    ppb  30.40  NaN
2019-06-01    O3    ppb  21.30  NaN
2019-07-01    O3    ppb  17.70  NaN
2019-01-01  PM10  μg/m3  31.00  NaN
2019-02-01  PM10  μg/m3  31.00  NaN
2019-03-01  PM10  μg/m3  40.00  NaN
2019-04-01  PM10  μg/m3  38.00  NaN
2019-05-01  PM10  μg/m3  31.00  NaN
2019-06-01  PM10  μg/m3  24.00  NaN
2019-07-01  PM10  μg/m3  22.00  NaN
2019-01-01   NOx    ppb  29.84  NaN
2019-02-01   NOx    ppb  25.26  NaN
2019-03-01   NOx    ppb  28.08  NaN
2019-04-01   NOx    ppb  27.25  NaN
2019-05-01   NOx    ppb  24.45  NaN
2019-06-01   NOx    ppb  25.25  NaN
2019-07-01   NOx    ppb  20.96  NaN
2019-01-01    NO    ppb   7.36  NaN
2019-02-01    NO    ppb   4.85  NaN
2019-03-01    NO    ppb   4.87  NaN
2019-04-01    NO    ppb   4.61  NaN
2019-05-01    NO    ppb   4.51  NaN
2019-06-01    NO    ppb   6.39  NaN
2019-07-01    NO    ppb   5.36  NaN
2019-01-01   NO2    ppb  22.49  NaN
2019-02-01   NO2    ppb  20.41  NaN
2019-03-01   NO2    ppb  23.20  NaN
2019-04-01   NO2    ppb  22.64  NaN
2019-05-01   NO2    ppb  19.94  NaN
2019-06-01   NO2    ppb  18.86  NaN
2019-07-01   NO2    ppb  15.60  NaN

**取出  2019/01 – 2019/07 SO2資料**

reindex resetindex

https://zhuanlan.zhihu.com/p/30053389

https://blog.csdn.net/jingyi130705008/article/details/78162758

多層索引

https://ithelp.ithome.com.tw/articles/10194235

https://www.itread01.com/content/1548203786.html

In [41]:
#利用多層索引

df = df.reset_index()
#df.reindex(columns=['監測項目','監測日期','單位','監測值','標註']) #reindex()需要将所有的行索引或者列名全部表示出来
df = df.set_index(keys = ["監測項目","監測日期"])
df

                  單位    監測值    標註
監測項目 監測日期
SO2  2019-01-01  ppb   1.90   NaN
     2019-02-01  ppb   2.00   NaN
     2019-03-01  ppb   1.90   NaN
     2019-04-01  ppb   2.50   NaN
     2019-05-01  ppb   2.00   NaN
...              ...    ...   ...
NO2  2019-10-01  ppb  17.96   NaN
     2019-11-01  ppb  19.64   NaN
THC  NaT         ppm    NaN  無此測項
NMHC NaT         ppm    NaN  無此測項
CH4  NaT         ppm    NaN  無此測項

[80 rows x 3 columns]

In [43]:
df.loc['SO2'].loc['2019/01':'2019/07']

             單位  監測值   標註
監測日期
2019-01-01  ppb  1.9  NaN
2019-02-01  ppb  2.0  NaN
2019-03-01  ppb  1.9  NaN
2019-04-01  ppb  2.5  NaN
2019-05-01  ppb  2.0  NaN
2019-06-01  ppb  2.0  NaN
2019-07-01  ppb  1.7  NaN